//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace framework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EAD_ShopifyEntities : DbContext
    {
        public EAD_ShopifyEntities()
            : base("name=EAD_ShopifyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Shopify_Users> Shopify_Users { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<Shopify_Item> Shopify_Item { get; set; }
    }
}
