//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shopify_Item
    {
        public int Item_Id { get; set; }
        public string Item_Key { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Picture1 { get; set; }
        public string Picture2 { get; set; }
        public string Picture3 { get; set; }
        public int PriceOld { get; set; }
        public int PriceNew { get; set; }
        public Nullable<int> Quantity { get; set; }
        public int Rating { get; set; }
        public string Item_Type { get; set; }
        public string Ex_Description { get; set; }
    }
}
